"""store quoted price for administration

Revision ID: 70db62a428b0
Revises: eaca029a2783
Create Date: 2026-10-05 11:50:05.934874
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70db62a428b0'
down_revision: Union[str, None] = 'eaca029a2783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_requests', sa.Column('quoted_amount', sa.Numeric(precision=12, scale=3), nullable=True))
    op.create_check_constraint(
        'ck_quote_request_amount_nonnegative',
        'quote_requests',
        'quoted_amount IS NULL OR quoted_amount >= 0',
    )
    op.create_check_constraint(
        'ck_quote_request_quoted_amount',
        'quote_requests',
        "status <> 'quoted' OR quoted_amount IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_quote_request_quoted_amount', 'quote_requests', type_='check')
    op.drop_constraint('ck_quote_request_amount_nonnegative', 'quote_requests', type_='check')
    op.drop_column('quote_requests', 'quoted_amount')
    # ### end Alembic commands ###
