"""add product image galleries

Revision ID: a3eb7f9855e6
Revises: dfc50421b288
Create Date: 2026-10-05 12:14:32.664394
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a3eb7f9855e6'
down_revision: Union[str, None] = 'dfc50421b288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=80), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('alt_texts', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_type IN ('image/jpeg', 'image/png', 'image/webp')", name='ck_product_image_content_type'),
    sa.CheckConstraint('size_bytes > 0', name='ck_product_image_size_positive'),
    sa.CheckConstraint('sort_order >= 0', name='ck_product_image_sort_order'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_product_images_product_order', 'product_images', ['product_id', 'is_active', 'sort_order'], unique=False)
    op.create_index('uq_product_image_primary', 'product_images', ['product_id'], unique=True, postgresql_where=sa.text('is_primary'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_product_image_primary', table_name='product_images', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_product_images_product_order', table_name='product_images')
    op.drop_table('product_images')
    # ### end Alembic commands ###
