"""create product catalog and ordering schema

Revision ID: b50cca395d96
Revises: 
Create Date: 2026-10-05 11:07:17.974135
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b50cca395d96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('fulfillment_method', sa.String(length=16), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fulfillment_method IN ('pickup', 'delivery')", name='ck_order_fulfillment'),
    sa.CheckConstraint("payment_method = 'cash_on_fulfillment'", name='ck_order_payment_method'),
    sa.CheckConstraint("status IN ('pending_review', 'confirmed', 'in_production', 'ready', 'completed', 'cancelled')", name='ck_order_status'),
    sa.CheckConstraint('total_amount >= 0', name='ck_order_total_nonnegative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_reference'), 'orders', ['reference'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('descriptions', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('product_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'code', name='uq_option_product_code')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'sku', name='uq_variant_product_sku')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=180), nullable=False),
    sa.Column('variant_name', sa.String(length=180), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selected_options', sa.JSON(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.CheckConstraint('line_total >= 0', name='ck_order_item_total_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_quantity_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_tiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('option_values', sa.JSON(), nullable=False),
    sa.Column('quantity_min', sa.Integer(), nullable=False),
    sa.Column('quantity_max', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantity_max >= quantity_min', name='ck_price_quantity_range'),
    sa.CheckConstraint('quantity_min > 0', name='ck_price_quantity_min_positive'),
    sa.CheckConstraint('total_price >= 0', name='ck_price_total_nonnegative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_tier_lookup', 'price_tiers', ['product_id', 'variant_id', 'quantity_min', 'quantity_max'], unique=False)
    op.create_table('quote_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=180), nullable=False),
    sa.Column('variant_name', sa.String(length=180), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selected_options', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_requests_reference'), 'quote_requests', ['reference'], unique=True)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=80), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('order_item_id', sa.Uuid(), nullable=True),
    sa.Column('quote_request_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status IN ('pending', 'approved', 'rejected')", name='ck_file_review_status'),
    sa.CheckConstraint('NOT (order_id IS NOT NULL AND quote_request_id IS NOT NULL)', name='ck_file_single_owner'),
    sa.CheckConstraint('size_bytes > 0', name='ck_file_size_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_quote_requests_reference'), table_name='quote_requests')
    op.drop_table('quote_requests')
    op.drop_index('ix_price_tier_lookup', table_name='price_tiers')
    op.drop_table('price_tiers')
    op.drop_table('order_items')
    op.drop_table('product_variants')
    op.drop_table('product_options')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_reference'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
