"""add whatsapp notification outbox

Revision ID: dfc50421b288
Revises: 70db62a428b0
Create Date: 2026-10-05 12:01:30.734567
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dfc50421b288'
down_revision: Union[str, None] = '70db62a428b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'sent', 'failed')", name='ck_notification_outbox_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_notification_outbox_attempts'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notification_outbox_dedupe')
    )
    op.create_index('ix_notification_outbox_delivery', 'notification_outbox', ['status', 'next_attempt_at'], unique=False)
    op.add_column('customers', sa.Column('locale', sa.String(length=2), server_default=sa.text("'fr'"), nullable=False))
    op.add_column('customers', sa.Column('whatsapp_opt_in', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'whatsapp_opt_in')
    op.drop_column('customers', 'locale')
    op.drop_index('ix_notification_outbox_delivery', table_name='notification_outbox')
    op.drop_table('notification_outbox')
    # ### end Alembic commands ###
