"""store quote fulfilment preferences

Revision ID: e11e9b8d28cc
Revises: b50cca395d96
Create Date: 2026-10-05 11:13:09.455269
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e11e9b8d28cc'
down_revision: Union[str, None] = 'b50cca395d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_requests', sa.Column('fulfillment_method', sa.String(length=16), nullable=False))
    op.add_column('quote_requests', sa.Column('delivery_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_requests', 'delivery_address')
    op.drop_column('quote_requests', 'fulfillment_method')
    # ### end Alembic commands ###
