"""enforce TND and valid fulfillment data

Revision ID: eaca029a2783
Revises: e11e9b8d28cc
Create Date: 2026-10-05 11:21:45.487477
"""
from typing import Sequence, Union



revision: str = 'eaca029a2783'
down_revision: Union[str, None] = 'e11e9b8d28cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
